name: smart_baby_band
description: Baby Monitor App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For pre-built beautiful animations (FadeInUp, Bounce, etc.)
  animate_do: ^3.3.4

  # For the "Frosted Glass" (Glassmorphism) effect easily
  glassmorphism: ^3.0.0

  # For modern Google fonts (instead of default system fonts)
  google_fonts: ^6.2.1
  fl_chart: ^0.66.0
  provider: ^6.1.5+1
  
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.4.0
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 
  uses-material-design: true
  assets:
    - images/