// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYU0__-HUZ4HblrMKUvweYH1QOLWKhl4',
    appId: '1:914653408170:web:1f06df5e12299b8c6f99d3',
    messagingSenderId: '914653408170',
    projectId: 'baby-test-1',
    authDomain: 'baby-test-1.firebaseapp.com',
    storageBucket: 'baby-test-1.firebasestorage.app',
    measurementId: 'G-XEWFGMLWN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTy5GZ0PouuQGISkKDNREX5mscBW92-NU',
    appId: '1:914653408170:android:a8f8faf2ff06eec26f99d3',
    messagingSenderId: '914653408170',
    projectId: 'baby-test-1',
    storageBucket: 'baby-test-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPFiUo7hAPD5HXxnryssHwkxDt2jzuls',
    appId: '1:914653408170:ios:d6300e3bb44cf0026f99d3',
    messagingSenderId: '914653408170',
    projectId: 'baby-test-1',
    storageBucket: 'baby-test-1.firebasestorage.app',
    iosBundleId: 'com.example.bb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrPFiUo7hAPD5HXxnryssHwkxDt2jzuls',
    appId: '1:914653408170:ios:d6300e3bb44cf0026f99d3',
    messagingSenderId: '914653408170',
    projectId: 'baby-test-1',
    storageBucket: 'baby-test-1.firebasestorage.app',
    iosBundleId: 'com.example.bb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYU0__-HUZ4HblrMKUvweYH1QOLWKhl4',
    appId: '1:914653408170:web:5e2dab45d1fa0a606f99d3',
    messagingSenderId: '914653408170',
    projectId: 'baby-test-1',
    authDomain: 'baby-test-1.firebaseapp.com',
    storageBucket: 'baby-test-1.firebasestorage.app',
    measurementId: 'G-S8GPBJKCN5',
  );
}
